CREATE TABLE USUARIO_INICIAL (ID INTEGER PRIMARY KEY, NOMBRE VARCHAR2(40), SUELDO_BASE INTEGER);
CREATE TABLE RESPALDO_USUARIOINICIAL(ID INTEGER , NOMBRE VARCHAR2(40), SUELDO_BASE INTEGER);



INSERT INTO USUARIO_INICIAL VALUES(1,'JUAN',3500);
INSERT INTO USUARIO_INICIAL VALUES(2,'ANA',6000);
INSERT INTO USUARIO_INICIAL VALUES(3,'ROGER',6000);

CREATE OR REPLACE PROCEDURE CONTAR(NUMERO OUT INTEGER)
AS
BEGIN
SELECT COUNT(*) INTO NUMERO FROM USUARIO_INICIAL;

DBMS_OUTPUT.PUT_LINE('ENCONTRADOS  '||NUMERO);
END;
/

DECLARE 
VALOR INTEGER;
BEGIN
CONTAR(VALOR);
END;
/


CREATE OR REPLACE PROCEDURE COPIAR 
AS
CURSOR CUR_USUARIO_INICIAL IS SELECT * FROM USUARIO_INICIAL;
BEGIN
FOR REC IN CUR_USUARIO_INICIAL LOOP
INSERT INTO RESPALDO_USUARIOINICIAL VALUES(REC.ID, REC.NOMBRE, REC.SUELDO_BASE);
END LOOP;
END;
/

CREATE OR REPLACE TRIGGER DISP_USUARIO_INICIAL BEFORE INSERT ON USUARIO_INICIAL FOR EACH ROW
DECLARE
VALOR INTEGER;
BEGIN
CONTAR(VALOR);
IF  VALOR = 3 THEN
COPIAR();
DELETE FROM USUARIO_INICIAL;
END IF;
END;
/

INSERT INTO USUARIO_INICIAL VALUES(4,'JOSE MANUEL',5600);
INSERT INTO USUARIO_INICIAL VALUES(5,'CARMEN',5000);
INSERT INTO USUARIO_INICIAL VALUES(6,'OVIDIO',4520);

INSERT INTO USUARIO_INICIAL VALUES(7,'ROQUE',8000);

SELECT * FROM USUARIO_INICIAL;
SELECT * FROM RESPALDO_USUARIOINICIAL;
DELETE  FROM USUARIO_INICIAL;
